### PR TITLE
Fix buffer overrun in drill tool numbers

### LINKED ISSUE #30: TALOS Security Advisory for Gerbv (TALOS-2021-1402)
Hello, 
The Cisco Talos team found a security vulnerability affecting Gerbv products. As this is a sensitive security issue, please advise if you can mark the issue private in Github before we include the details of the report.

For further information about the Cisco Vendor Vulnerability Reporting and Disclosure Policy please refer to this document which also links to our public PGP key. https://tools.cisco.com/security/center/resources/vendor_vulnerability_policy.html Please CC vulndev@cisco.com all correspondence related to this issue.

### PR DESCRIPTION
**Pull request by eyal0**
This fixes #30

### CODE REVIEW

**Comment by CiscoTalos** [comment]
Please confirm when this issue is ready for public disclosure. Thanks!

**Comment by ooxi** [comment]
@CiscoTalos TALOS-2021-1402 is ready for public disclosure. It has been fixed in both the main development branch and was also backported and released as [2.7.1](https://github.com/gerbv/gerbv/releases/tag/gerbv-2-7-1-RELEASE).

We will inform the main distributions (Debian, Fedora, Ubuntu) of this issue as soon as you green light us. We don't want to take away from your publication by jumping the gun :-)

**Comment by CiscoTalos** [comment]
We have released our advisory on https://talosintelligence.com/vulnerability_reports/TALOS-2021-1402. We will also be issuing a statement to direct people to the corrected version on GitHub instead of Sourceforge.

**Comment by CiscoTalos** [comment]
If you 're interested in fuzzing with AFL, the commands below show how to compile gerbv and run it with AFL using ASAN in a very simplistic way, but should be useful as a starting point. You have plenty of things to configure, like ASAN_OPTIONS and AFL env variables.

Note that the source needs to be patched ([fuzzing.patch.txt](https://github.com/gerbv/gerbv/files/7478502/fuzzing.patch.txt)) to prevent glib from sending sigtraps, which would be considered as crashes by AFL.

```
git clone https://github.com/gerbv/gerbv.git
patch -p1 < ../fuzzing.patch.txt
./autogen.sh
export AFL_USE_ASAN=1
./configure CC="afl-gcc" CXX="afl-g++" --disable-update-desktop-database --disable-shared --prefix $PWD/../build
make
make install
cd ../build
mkdir in out
echo > in/someinputfile
sudo sh -c 'echo core >/proc/sys/kernel/core_pattern'
sudo sh -c 'cd /sys/devices/system/cpu; echo performance | tee cpu*/cpufreq/scaling_governor'
export LD_LIBRARY_PATH=./lib
afl-fuzz -i in -o out -m none -- ./bin/gerbv -x png -o out.png @@
```

However since yours is an opensource project, we'd suggest to consider running it in [OSS-Fuzz](https://google.github.io/oss-fuzz/).

**Pull request merged**
