### PR TITLE
Linux packaging: pass command line arguments from gerbv.sh

### PR DESCRIPTION
**Pull request by PetteriAimonen**
Gerbv has a nice command line interface.
This commit allows using it through the gerbv.sh wrapper script also.

### CODE REVIEW

**Comment by eyal0** [comment]
Seems okay to me but I don't know how to test it.  @PetteriAimonen have you tried this and seen that it works as expected?

**Comment by PetteriAimonen** [comment]
I have tried it by editing the `"$@"` into the gerbv.sh in the package downloaded from https://gerbv.github.io/#download

But the CI didn't run for me (seems to be missing `apt-get update`?) so I didn't test a fully rebuilt package.

To test one could do:

1. Run `./gerbv.sh` without arguments, to confirm it runs the GUI as before.
2. Run `./gerbv.sh --help` to see that the command line arguments get passed to it.

**Comment by eyal0** [comment]
CI was broken. If you rebase then it should pass. Try again please?

**Comment by PetteriAimonen** [comment]
Hmm yeah, builds now, but for some reason I cannot see the build results on my own fork. I guess the CI job could benefit from `actions/upload-artifact`.

**Pull request merged**
