### PR TITLE
Fix SVG export scale for Cairo 1.17.6+

### LINKED ISSUE #231: Gerbv scales down when I export to SVG
I have this example gerber file with two "circles". The distance between them is 2.54mm. If I export to PDF and then open in Inkscape the distance is still 2.54mm. But if I export to SVG the distance is scaled down to 1.91mm. Everything is scaled down and you can't realize it until you measure it or print it. The same happens with the Print option.

This happens in Arch Linux with the latest version (from AUR) 2.10.0 but also with 2.9.5. I had to use Windows 7 with this version gerbv-win-static_20160713 to properly export my files.
[samples.zip](https://github.com/gerbv/gerbv/files/13619507/samples.zip)

The bug is present in version gerbv-2.7.0. This is the oldest version available to download from archive.archlinux.org so I can't test earlier versions.

### PR DESCRIPTION
**Pull request by PingPongun**
Fixes #231

### CODE REVIEW

**Comment by spe-ciellt** [comment]
Thank you for finding the problem and submitting a fix. I have one question before merging this. Is the #if necessary?  If you have that line using an older version of libcairo, will it break anything? I would like to have that patch, but without the #if/#endf (if possible). It feels better to always make sure we use the correct units. Maybe a comment on the Cairo versioning thing?

**Comment by PingPongun** [comment]
The function `cairo_svg_surface_set_document_unit`
Has been added in 1.16 so without `if`s it will break for Cairo bellow 1.16

**Comment by spe-ciellt** [comment]
OK, great, then I know. It looks a bit like the formatting is a bit off. The #if/#endif should be on the column and the code added should have spaces and not tabs (I guess you are using). If you look at the diff in Github you see the difference.
We have a .clang-format, so you can use that to check the formatting.

**Comment by PingPongun** [comment]
I believe formatting should now be correct

**Comment by PingPongun** [comment]
Corrected (and this time (previously I was to lazy) I've also built it locally and tested- it fixes issue at least for me)

**Comment by PingPongun** [comment]
I've updated code so that it will also work when using `File>>Print` (previous one worked with cli export and `File>>Export>>SVG`, as mentioned in https://github.com/gerbv/gerbv/issues/231#issuecomment-2267650758)

**Comment by spe-ciellt** [comment]
@PingPongun  I merged this now. Thank you for your patch and rework!

**Pull request merged**
