### PR TITLE
Live edit

### PR DESCRIPTION
**Pull request by Rix**
continuation of PR #70 :

* For scale, rotation and mirroring operations on layer edit window
* Scaling on single axis was impractical, so "Maintain aspect ratio" option added as default.
* "Apply to Active" button seems a little bit non-functional, but still remains there.

### CODE REVIEW

**Comment by ooxi** [comment]
Thank you very much! You seem have experience with GTK programming. Do you happen to have experience with GTK4, too?

**Comment by ooxi** [comment]
5dfc9af37a7871811e760839d8bc0aa49d51221c is now cherry-picked as 10746b8ee8579a967576a4fc303f80c9b1af7f28. Please use a new feature branch for the next PR, otherwise the GitHub GUI gets confused :-)

**Comment by Rix** [comment]
Your welcome! I only have some experience with GTK# on Mono, but not C. But, library structure looks similar to other GUI toolkits, so I was able to find the keywords quickly that I need on web search.

**Comment by ooxi** [comment]
@Rix fyi your new features are released in [v2.8.1](https://github.com/gerbv/gerbv/releases/tag/v2.8.1)

**Comment by Rix** [comment]
Thank you ! Hope to contribute more in the next release :)
Are new releases also being put into sourceforge gerbv repo ?

**Comment by ooxi** [comment]
> Are new releases also being put into sourceforge gerbv repo ?

@Rix the GitHub project was created since the maintainers of the SourceForge project fell silent (after doing excellent work in the past). Therefore we have no access to the SourceForge repository to push releases there, too.

**Pull request closed without merging**
