### PR TITLE
IPC-D-356A testpoint data support plus RS274-X2 attributes.

### PR DESCRIPTION
**Pull request by meantaipan**
This is for issue #157.

Hopefully you can squash the commit history if you pull.  Otherwise, let me know and I'll make a squashed branch.

### CODE REVIEW

**Comment by ooxi** [comment]
The ci-coverage failing is not an issue, but somehow the tests itself do not seem to run. Did they pass in your fork?

**Comment by meantaipan** [comment]
@ooxi yes all tests passed, but I had to regen some of the "golden" PNG files.

This test failed on the pick and place example.  This was one I had to regen.  It is probably failing for you because of minor differences when rendering text (exact typeface used, pixel-level differences etc.)

This is a weakness in the automated tests that probably needs to be resolved.  Rather than comparing the test output with a single golden PNG, it needs to compare with a set of them, and only fail if none match.  So if the test name is 'foo' then it will compare with foo.png, foo$ubuntu16.04.png, foo$raspberrypi.png and so on.

For now, I would bypass the pick and place test.  I think it's the only one that writes text.

**Comment by eyal0** [comment]
I'm not able to build your code on my computer yet.  I'll keep trying...

**Comment by eyal0** [comment]
@meantaipan Can you please try the following commands:

```bash
git co meantaipan/main
git rebase gerbv/main -x "make -j 20 clean && make -j 20 && (make check || (cd test ; ./run_tests.sh --regen ; cd .. ; make check))"
```

This will check that every commit is code that can be compiled and it will also update the golden files at each step.  This will show us which change is the one that causes the golden files to change.

The golden files work on my computer and also in CI and the CI platform hasn't changed so I would expect that the tests would continue to pass, right?

**Comment by meantaipan** [comment]
@eyal0 Only change to rendered output is for the pick and place example, which writes text.  Everything not involving text should be exactly the same.

**Comment by eyal0** [comment]
@meantaipan After the rebase stuff completes then I'll push the update and we'll see which change made the difference, yes?

**Comment by meantaipan** [comment]
@eyal0 OK, I'm curious to know.  I'm certainly not a git guru.  My version doesn't even understand "git co".

**Comment by eyal0** [comment]
> @eyal0 OK, I'm curious to know. I'm certainly not a git guru. My version doesn't even understand "git co".

Oops, haha, `co` is short for `checkout`!

I see that the tests are failing on valgrind, too, which means that there is a new memory leak.  We'll look for that also.

**Comment by meantaipan** [comment]
@eyal0 That's embarrassing.  Don't worry, I know how to use valgrind, so I can look into that (but not until this evening California time, about 8 hours away).

**Comment by eyal0** [comment]
Oops I did a bad push.  It's confusing me very much that your branch and this branch are both called main!

Let's not call the feature branch `main` please

**Comment by meantaipan** [comment]
@eyal0 Yeah my bad.  My local repo uses a different branch name, but for some dumb reason I pushed to main on my github fork.  Know better now.

**Comment by eyal0** [comment]
I re-opened on a different branch because my bad push closed this one.  I also see some warnings.  Anyway, take a look at #161 and address those.  And then you can rebase and put it on your own branch in your own fork of the repo if you want, no problem.

**Pull request closed without merging**
