### PR TITLE
Unify header include guards as https://github.com/gerbv/gerbv/issues/26

### PR DESCRIPTION
**Pull request by efa**
Unify header include guards as https://github.com/gerbv/gerbv/issues/26
Where missing, added #if defined(__cplusplus)
                     extern "C" {
                     #endif
Where miss set head comments all the same, with GNU GPL copyright notice

### CODE REVIEW

**Comment by efa** [comment]
unfortunately the check do not passed. Looking in the log I saw two tests failed, one for different output and the other for a segmentation fault. I tryed to run the checks manually and fail the same. Previously I built run and check manually if gerbv seems work and that pass.
So I will re-clone the original repo, and replacing one .h file by .h file, I will recompile to try determine which one generate the trouble. This is not a fast task, as the .h files are 30.

**Comment by efa** [comment]
without `opdefines.h` modified I have no segmentation fault

**Comment by efa** [comment]
new CI fail because configure dxflib while I locally not configure it, and dxflib is in C++
Will try to fix also that

**Comment by efa** [comment]
there was two `#ifdef __cplusplus`, removed.
Now while I locally I got no error, CI fail with:
```
libtool: compile:  g++ -DLOCALEDIR=\"/usr/local/share/locale\" -DHAVE_CONFIG_H -I. -I.. -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/libxml2 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/atk-1.0 -pthread -DPREFIXDIR=\"/usr/local\" -DBINDIR=\"/usr/local/bin\" -g -O2 -MT export-dxf.lo -MD -MP -MF .deps/export-dxf.Tpo -c export-dxf.cpp  -fPIC -DPIC -o .libs/export-dxf.o
In file included from /usr/include/glib-2.0/glib/gatomic.h:31,
                 from /usr/include/glib-2.0/glib/gthread.h:32,
                 from /usr/include/glib-2.0/glib/gasyncqueue.h:32,
                 from /usr/include/glib-2.0/glib.h:32,
                 from gerbv.h:78,
                 from export-dxf.cpp:27:
/usr/include/c++/11/type_traits:56:3: error: template with C linkage
   56 |   template<typename _Tp, _Tp __v>
      |   ^~~~~~~~
```

**Comment by efa** [comment]
OK, I moved the `#ifdef __cplusplus` 13 lines below, now work

**Comment by efa** [comment]
as I used force push on my repo, you should apply only the last commit, and should be no conflicts

**Comment by ooxi** [comment]
Thank's again for the effort @efa! I really like the unification of header include guards to a pattern like `GERBV_AMACRO_H` which you used :-)

Nevertheless I think it is important that we keep the scope of individual commits reasonable and while checking the changes in 6a039cd334c66d63c1c82be3a43e563f808bc7be I happen to notice changes to name mangling as well as licenses besides the actual include guard changes.

| Header | Comment |
| --- | --- |
| [amacro.h](https://github.com/gerbv/gerbv/pull/29/commits/6a039cd334c66d63c1c82be3a43e563f808bc7be#diff-68c933e26a34c82039c0b67652cf85c5c956404c0ac39374eef178f6e2bd6b7e) | Looks good to me 👍 |
| [attribute.h](https://github.com/gerbv/gerbv/pull/29/commits/6a039cd334c66d63c1c82be3a43e563f808bc7be#diff-faec7ad3add3ee8f27bb3b6a4f7f79b3dfb71e2711ab735ccb002dfb3fed9210) | We cannot change from `GPL-2.0-only` to `GPL-2.0-or-later` without a separate discussion |
| [callbacks.h](https://github.com/gerbv/gerbv/pull/29/commits/6a039cd334c66d63c1c82be3a43e563f808bc7be#diff-039131a12da0afa67d978db92c0ee6f8abfc9a44f817e702bb6228af73500ff2) | I agree with the name mangling change but this should be done in a separate commit |
| [common.h](https://github.com/gerbv/gerbv/pull/29/commits/6a039cd334c66d63c1c82be3a43e563f808bc7be#diff-649a0b286b520f22da501867c812f1acbc760fe028ea70edb14b60672ba7c716) | License + Name mangling |
| [csv.h](https://github.com/gerbv/gerbv/pull/29/commits/6a039cd334c66d63c1c82be3a43e563f808bc7be#diff-2b73f0ed0a03b8698a47ad696b52225430ce88beedca3812bf6ea423e5d8ac5b) | Looks good to me 👍 |
| [csv_defines.h](https://github.com/gerbv/gerbv/pull/29/commits/6a039cd334c66d63c1c82be3a43e563f808bc7be#diff-412d2c6d534e2e2597bff93ef125afa0265225b39f4f925447de8eb5bce26029) | License + Name mangling, moreover I would have used the define `GERBV_CSV_DEFINES_H` |
| [draw-gtk.h](https://github.com/gerbv/gerbv/pull/29/commits/6a039cd334c66d63c1c82be3a43e563f808bc7be#diff-2e7e8d775dae5aa3068cc4abac86148f90110d94bb82f84372038669fe76d021) | Name mangling should not be changed for includes |
| [draw.h](https://github.com/gerbv/gerbv/pull/29/commits/6a039cd334c66d63c1c82be3a43e563f808bc7be#diff-27c624ceb5eeb0d3d17fb8f0cda8301d059a2997782ad6359865f51a0fe79878) | Name mangling should not be changed for includes |
| [drill.h](https://github.com/gerbv/gerbv/pull/29/commits/6a039cd334c66d63c1c82be3a43e563f808bc7be#diff-9c852ad2cce63f86a12d3d5adcae3dcdc6b8df49aa285db6dce6f0e6b8fbadd4) | Looks good to me 👍 |
| [drill_stats.h](https://github.com/gerbv/gerbv/pull/29/commits/6a039cd334c66d63c1c82be3a43e563f808bc7be#diff-e31c1d70bb847932601c41162e8a16ba5b172a599801b00231dda08e1d22cdbe) | Name mangling should not be changed for includes |
| [dynload.h](https://github.com/gerbv/gerbv/pull/29/commits/6a039cd334c66d63c1c82be3a43e563f808bc7be#diff-5423f78b9d2cd7162534df55ff8d3a00d195286e469c1e6b5ad40835625e6c84) | License + Name mangling |
| [gerb_file.h](https://github.com/gerbv/gerbv/pull/29/commits/6a039cd334c66d63c1c82be3a43e563f808bc7be#diff-576f108a9ffd758955c3ecb7a90523f8dc81cb0fa7f98632cdfaab141926e292) | Name mangling should not be changed for includes |
| [gerb_image.h](https://github.com/gerbv/gerbv/pull/29/commits/6a039cd334c66d63c1c82be3a43e563f808bc7be#diff-65ff16aeaee2e12cc7392207c9c3ab567245b42a7211d72e905e17baf80c00c6) | I'm not sure why we moved the includes into the name mangling block, otherwise good |
| [gerb_stats.h](https://github.com/gerbv/gerbv/pull/29/commits/6a039cd334c66d63c1c82be3a43e563f808bc7be#diff-59d5c815b407c7d12cdd018335f941f4181895f34c91a69da67cccb113e14127) | Name mangling, otherwise good |
| [gerber.h](https://github.com/gerbv/gerbv/pull/29/commits/6a039cd334c66d63c1c82be3a43e563f808bc7be#diff-a2aa9c4068b884791954a32edae20f5ef354a63d2396c8c9ea0172f9c165df37) | Looks good to me 👍 |
[ [gerbv.h](https://github.com/gerbv/gerbv/pull/29/commits/6a039cd334c66d63c1c82be3a43e563f808bc7be#diff-3802cbcdb0af8c0a04ec0fc67cab4d18dbed5f686c2b6cad1d836323c0b64bbd) | Looks good to me 👍 |
| [gerbv_icon.h](https://github.com/gerbv/gerbv/pull/29/commits/6a039cd334c66d63c1c82be3a43e563f808bc7be#diff-ca48eee36960911a10dc8db29fb0b182e574e1a9a592a9eecd2dc36071f1c797) | While I think we shouldn't change generated files, im OK with this. License should however be discussed |
| [gettext.h](https://github.com/gerbv/gerbv/pull/29/commits/6a039cd334c66d63c1c82be3a43e563f808bc7be#diff-cb5bbe709f9fd5ebe4387d5c0f3c2574ff705d4735f3840e04b1322f1494a709) | We should not change vendored headers, otherwise this might lead to multiple definitions of the same symbol. Nevertheless we should check why this header is vendored in the first place |
| [icons.h](https://github.com/gerbv/gerbv/pull/29/commits/6a039cd334c66d63c1c82be3a43e563f808bc7be#diff-2795d52020b5e89a861c952c17e4a9cc2aee8a913784feb5d4c23fd1d280bcfd) | Also a generated file with license change |
| [interface.h](https://github.com/gerbv/gerbv/pull/29/commits/6a039cd334c66d63c1c82be3a43e563f808bc7be#diff-a53499c8d9cd8b352ec5c5f2c6e050e28ed90cc295ce7ac4a81a2b795000b6ab) | Name mangling |
| [lrealpath.h](https://github.com/gerbv/gerbv/pull/29/commits/6a039cd334c66d63c1c82be3a43e563f808bc7be#diff-7f6de6d25a86945f472ec15573d8972432553afbabb4d1288394a91c8e97b860) | License + Name mangling |
| [main.h](https://github.com/gerbv/gerbv/pull/29/commits/6a039cd334c66d63c1c82be3a43e563f808bc7be#diff-910d89612d74e91ae70ed40289b3910b1c1a09b1f5a1bb0b15849f70760cbba2) | Looks good to me 👍, this header seems to be broken before |
| [pick-and-place.h](https://github.com/gerbv/gerbv/pull/29/commits/6a039cd334c66d63c1c82be3a43e563f808bc7be#diff-c272407b5795a43f0fe27748bfc42e9e4532588aa125bf485cad540d27196e5a) | Name mangling |
| [project.h](https://github.com/gerbv/gerbv/pull/29/commits/6a039cd334c66d63c1c82be3a43e563f808bc7be#diff-160027d71936304387f551d0509e48292eab3429e467ec097ad56f80e2ebb544) | Name mangling |
| [render.h](https://github.com/gerbv/gerbv/pull/29/commits/6a039cd334c66d63c1c82be3a43e563f808bc7be#diff-995f5ae9cdef8eb163afc18d04ea1d6b96dd980257d82f5d778edbf1008f0932) | License + Name mangling |
| [scheme-private.h](https://github.com/gerbv/gerbv/pull/29/commits/6a039cd334c66d63c1c82be3a43e563f808bc7be#diff-82c2cc9a36f4c1ce91a3361596f8600337c602fc58f07d9e3a717343acf88b24) | License + Name mangling |
| [scheme.h](https://github.com/gerbv/gerbv/pull/29/commits/6a039cd334c66d63c1c82be3a43e563f808bc7be#diff-d951593c9916dc9e6a44c5e767d79c1521ec0af85fb575d2fc24b5b0642b0b34) | License + Name mangling of includes |
| [selection.h](https://github.com/gerbv/gerbv/pull/29/commits/6a039cd334c66d63c1c82be3a43e563f808bc7be#diff-f64f70603268c7b1c310f008cb4868e9fd810785e85fd10a0309e4e3931345f0) | License + Name mangling |
| [table.h](https://github.com/gerbv/gerbv/pull/29/commits/6a039cd334c66d63c1c82be3a43e563f808bc7be#diff-a6c5e7e05c62a752651ea920f189fb06d9f16a0fbc940ebe90d740738639d0e2) | License + Name mangling |

Again, thank you very much for your work and I think we are on the right track. We should should just separate those changes to discuss them individually:

1. Let's merge just the include guard change
2. Let's add correct name mangling but keep in mind to not change mangling of other includes (like `extern "C" { #include <stuff.h> }` might break inside `stuff.h`)
3. Let's discuss license changes / clarifications on a per header basis

I it would be great if you can support me with those changes. Nevertheless I would totally understand if you prefer to not do this work in which case I would split your commit into multiple but credit you with the changes.

**Pull request closed without merging**
