### PR TITLE
build: Check for git before making the version

### PR DESCRIPTION
**Pull request by eyal0**
This fixes https://github.com/gerbv/gerbv/issues/130
This fixes https://github.com/pcb2gcode/pcb2gcode/issues/626

### CODE REVIEW

**Review by ooxi — APPROVED** [review]

**Comment by ooxi** [comment]
Thank you! I'm not quite sure why the build succeeded with git missing, but in those cases using the prefix instead of the actual version is fine.

**Comment by ooxi** [comment]
I think we should do a new patch release soon, before adding bigger changes. I'll try to make time this week but feel free to go ahead.

**Comment by ooxi** [comment]
@eyal0 I have created the release [v2.9.3-rc.1](https://github.com/gerbv/gerbv/releases/tag/v2.9.3-rc.1). Do know a way to verify whether this fixes the issue experienced by maintainers?

**Comment by eyal0** [comment]
1. Download the .tar.gz files from the releases page. Don't do it in a git repo.
2. Decompress it.
3. Build the usual way.
4. Confirm that the generated file `libgerbv.pc` contains a version number.

**Comment by eyal0** [comment]
Here are the commands that I typed to check it:

```bash
wget 'https://github.com/gerbv/gerbv/archive/refs/tags/v2.9.3-rc.1.tar.gz'
tar xvf gerbv-2.9.3-rc.1.tar.gz
cd gerbv-2.9.3-rc.1
./autogen.sh 
./configure
make -j 20
grep "Version" ./src/libgerbv.pc
```

I got:

```
Version: 2.9.3-rc.1
```

Looks good!  The same commands on 2.9.2 do not make a valid Version:

```
Version:
```

Perfect.  This ought to solve the problem.  Hopefully the maintainers of the ubuntu and arch package will get around to shipping a new one soon.

**Comment by hachi** [comment]
Ubuntu shipped a new version in lunar I think... but I don't think the checks for git are enough. You may be inside a git working tree from some other project (the package maintainers) and as a result the .pc file will still not have a Version: marked properly.

https://packages.ubuntu.com/lunar/gerbv # I believe 2.9.6 build should have included your fix.

**Comment by eyal0** [comment]
And it still doesn't have the fix.  :-(  I just unpacked that debian file and the version is not there.  Oh no!

Is the maintainer, like... a human?  Someone that we can talk to?  I tried sending a bug report and emailing someone but I got not response.

**Comment by hachi** [comment]
@eyal0 I thought you are the maintainer

**Comment by eyal0** [comment]
Nope.  There are people that update the gerbv package for Ubuntu but I'm not that person.

**Pull request merged**
