### PR TITLE
test: Regenerate all golden files

### LINKED ISSUE #15: ./run_test fails on Unix
To reproduce, make and install the code and then:

```
cd test
./run_tests.sh
```

I'm seeing this result:

```
Passed 67, failed 23, skipped 0 out of 90 tests.
```

I'll start with a git bisect to see where it was introduced.

### PR DESCRIPTION
**Pull request by eyal0**
The unit testing has not been working for a long time.  This
regnerates the golden files so that we can start fresh.

This fixes #15

### CODE REVIEW

**Comment by ooxi** [comment]
This is looking good @eyal0! I'm not sure if inviting you to the organization was sufficient to give you the possibility to accept pull requests yourself. If not, please ping me :-)

If possible I would prefer rebase and merge for simple PRs (one commit) and merge for more complex features with multiple commits. Is this ok with you?

**Comment by eyal0** [comment]
Looking at Files changed, if I click on the "rich diff" button in GitHub and then switch to "Swipe" mode, I can see the differences  They are there and they are visible.  It's probably too much work to go through and investigate each one.  For each diff, we'd need to determine if gerbv is doing a better job or a worse job.  And then perhaps go back and fix things.

Probably no one will ever get around to doing that so I suggest that we just commit this regeneration.  Let's not let _perfect_ be the enemy of _good_.

**Comment by ooxi** [comment]
> Probably no one will ever get around to doing that so I suggest that we just commit this regeneration. Let's not let perfect be the enemy of good.

I agree with your assesment!

**Comment by eyal0** [comment]
Seems that I'm unable to merge.  I don't have [write access](https://docs.github.com/articles/what-are-the-different-access-permissions).  Either @ooxi does it or I get permission.  I'm okay either way.

**Comment by ooxi** [comment]
Could you please try to merge again @eyal0? I'm fine with merging this but I want to make sure you are able to accept pull requests in the future, too :-)

I had to separately give you write access to this repository, while thinking inviting you to the organization was sufficient.

**Pull request merged**
